name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Bundle Install
      run: |
        bundle install

    - name: Compile C extension
      run: bundle exec rake compile

    - name: Move shared object to script directory
      run: mv tmp/x86_64-linux/stage/lib/example.so ./ # adjust paths accordingly

    - name: Run tests
      run: ruby script.rb

